### ISSUE TITLE
프로젝트 초기 환경 세팅

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-MSE-DreamTeam/backend#1]
## 🔥 Issue
프로젝트 초기 환경 세팅

## ✅ TODO
- [x] Pull request template 추가
- [x] Logging 환경 구축
- [x] Swagger 의존성 추가 및 설정
- [x] Error handling 환경 구축
