### ISSUE TITLE
Client 요청사항에 따른 응답 데이터 변경

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-MSE-DreamTeam/backend#19]
## 🔥 Issue
이슈 관련 내용을 입력하세요.

## ✅ TODO
- [x] 대기실 목록 조회 시 응답 데이터에 호스트의 닉네임 추가.
- [x] 플레이어 정보에 회원 닉네임 데이터 추가
- [x] 게임 시작 여부 확인 시 플레이어들의 준비 상태도 확인 가능하도록 응답 데이터 추가.
