### ISSUE TITLE
게임 종료 및 게임 기록 저장/조회 기능 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-MSE-DreamTeam/backend#44]
## 🔥 Issue
게임 종료 및 게임 기록 저장 기능 구현

## ✅ TODO
- [x] 게임 종료 조건 확인 로직 추가
- [x] 게임 종료 시 기록 저장을 위한 기능 구현
- [x] 저장된 게임 기록을 조회할 수 있는 API 구현
