### ISSUE TITLE
로비, 게임 룸(`Room`) 관련 기능 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-MSE-DreamTeam/backend#9]
## 🔥 Issue
로비, 게임 룸(`Room`) 관련 기능 구현

## ✅ TODO
- [x] 게임 룸 생성 기능 구현
- [x] 게임 룸 참여 기능 구현
- [x] 현재 대기중인 게임 룸(대기실) 목록 조회 기능 구현
- [x] 게임 룸의 게임시작 여부 확인 기능 구현
- [x] 게임 시작 기능 구현

**Comment by Wo-ogie** [comment]
깜빡하고 미구현된 기능이 있어 issue reopen.
